services:
  - type: web
    name: trung-cang-his
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login
    autoDeployTrigger: checksPass
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        sync: false
      - key: JDBC_DATABASE_USERNAME
        sync: false
      - key: JDBC_DATABASE_PASSWORD
        sync: false
      - key: BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
