-- Bổ sung 100 ICD từ DM_ICD.xls; chỉ thêm mã chưa có, không ghi đè dữ liệu.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO diagnoses (icd_code,name,description,status) VALUES
('R00.0','Nhịp tim nhanh, không xác định','Tachycardia, unspecified','ACTIVE'),
('R05','Ho','Cough','ACTIVE'),
('R06.0','Khó thở','Dyspnoea','ACTIVE'),
('R10.0','Đau bụng cấp tính','Acute abdomen','ACTIVE'),
('R10.1','Đau khu trú bụng trên','Pain localized to upper abdomen','ACTIVE'),
('R10.4','Đau bụng khác và/hoặc không xác định','Other and unspecified abdominal pain','ACTIVE'),
('R12','Ợ nóng [đau rát ngực]','Heartburn','ACTIVE'),
('R14','Đầy hơi và/hoặc tình trạng liên quan','Flatulence and related conditions','ACTIVE'),
('R21','Ban da và/hoặc phát ban không xác định cụ thể','Rash and other nonspecific skin eruption','ACTIVE'),
('R50.9','Sốt, không xác định','Fever, unspecified','ACTIVE'),
('R51','Đau đầu','Headache','ACTIVE'),
('R53','Khó chịu và/hoặc mệt mỏi','Malaise and fatigue','ACTIVE'),
('A09','Viêm dạ dày - ruột và/hoặc đại tràng do nhiễm trùng và/hoặc không xác định căn nguyên','Other gastroenteritis and colitis of infectious and unspecified origin','ACTIVE'),
('A09.0','Viêm dạ dày - ruột và/hoặc đại tràng do nhiễm trùng khác và/hoặc không xác định','Other and unspecified gastroenteritis and colitis of infectious origin','ACTIVE'),
('A09.9','Viêm dạ dày - ruột và/hoặc đại tràng không xác định căn nguyên','Gastroenteritis and colitis of unspecified origin','ACTIVE'),
('B02.9','Bệnh zona không biến chứng','Zoster without complication','ACTIVE'),
('B18.1','Bệnh viêm gan virus B mạn tính không có viêm gan D [tác nhân delta]','Chronic viral hepatitis B without delta-agent','ACTIVE'),
('B18.2','Bệnh viêm gan virus C mạn tính','Chronic viral hepatitis C','ACTIVE'),
('B35.3','Bệnh nấm da chân','Tinea pedis','ACTIVE'),
('B35.4','Bệnh nấm da thân','Tinea corporis','ACTIVE'),
('B37.0','Bệnh viêm miệng do nhiễm nấm candida','Candidal stomatitis','ACTIVE'),
('D50.9','Thiếu máu thiếu sắt, không xác định','Iron deficiency anaemia, unspecified','ACTIVE'),
('D64.9','Thiếu máu, không xác định','Anaemia, unspecified','ACTIVE'),
('E03.9','Suy tuyến giáp, không xác định','Hypothyroidism, unspecified','ACTIVE'),
('E05.9','Nhiễm độc tuyến giáp [cường giáp], không xác định','Thyrotoxicosis, unspecified','ACTIVE'),
('E11.9','Bệnh đái tháo đường típ 2, không kèm biến chứng','Type 2 diabetes mellitus, without complications','ACTIVE'),
('E14.9','Đái tháo đường không xác định, không kèm biến chứng','Unspecified diabetes mellitus, without complications','ACTIVE'),
('E66.9','Bệnh béo phì, không xác định','Obesity, unspecified','ACTIVE'),
('E78.0','Tăng cholesterol máu đơn thuần','Pure hypercholesterolaemia','ACTIVE'),
('E78.1','Tăng triglycerid máu đơn thuần','Pure hyperglyceridaemia','ACTIVE'),
('E78.5','Tăng lipid máu, không xác định','Hyperlipidaemia, unspecified','ACTIVE'),
('E86','Giảm thể tích','Volume depletion','ACTIVE'),
('F41.1','Rối loạn lo âu tổng quát','Generalized anxiety disorder','ACTIVE'),
('G43.9','Bệnh đau nửa đầu [migraine], không xác định','Migraine, unspecified','ACTIVE'),
('G44.2','Đau đầu do căng thẳng','Tension-type headache','ACTIVE'),
('G47.0','Rối loạn vào giấc và/hoặc rối loạn duy trì giấc ngủ [chứng mất ngủ]','Disorders of initiating and maintaining sleep [insomnias]','ACTIVE'),
('H00.0','Lẹo và/hoặc viêm sâu khác của mi mắt','Hordeolum and other deep inflammation of eyelid','ACTIVE'),
('H10.9','Viêm kết mạc, không xác định','Conjunctivitis, unspecified','ACTIVE'),
('H16.9','Viêm giác mạc, không xác định','Keratitis, unspecified','ACTIVE'),
('H40.9','Glôcôm, không xác định','Glaucoma, unspecified','ACTIVE'),
('H52.1','Cận thị','Myopia','ACTIVE'),
('H60.9','Viêm tai ngoài, không xác định','Otitis externa, unspecified','ACTIVE'),
('H65.9','Viêm tai giữa không có mủ, không xác định','Nonsuppurative otitis media, unspecified','ACTIVE'),
('H66.9','Viêm tai giữa, không xác định','Otitis media, unspecified','ACTIVE'),
('H81.1','Chóng mặt kịch phát lành tính','Benign paroxysmal vertigo','ACTIVE'),
('I20.9','Cơn đau thắt ngực, không xác định','Angina pectoris, unspecified','ACTIVE'),
('I25.9','Bệnh tim thiếu máu cục bộ mạn tính, không xác định','Chronic ischaemic heart disease, unspecified','ACTIVE'),
('I48','Rung nhĩ và/hoặc cuồng nhĩ','Atrial fibrillation and flutter','ACTIVE'),
('I83.9','Giãn tĩnh mạch chi dưới không loét hoặc viêm','Varicose veins of lower extremities without ulcer or inflammation','ACTIVE'),
('I95.9','Hạ huyết áp, không xác định','Hypotension, unspecified','ACTIVE'),
('J01.9','Viêm xoang cấp tính, không xác định','Acute sinusitis, unspecified','ACTIVE'),
('J02.9','Viêm họng cấp tính, không xác định','Acute pharyngitis, unspecified','ACTIVE'),
('J03.9','Viêm amydan cấp tính, không xác định','Acute tonsillitis, unspecified','ACTIVE'),
('J10.1','Cúm với biểu hiện hô hấp khác, đã xác định được virus cúm mùa','Influenza with other respiratory manifestations, seasonal influenza virus identified','ACTIVE'),
('J11.1','Cúm có biểu hiện hô hấp khác, không xác định được virus','Influenza with other respiratory manifestations, virus not identified','ACTIVE'),
('J18.9','Viêm phổi, không xác định','Pneumonia, unspecified','ACTIVE'),
('J30.1','Viêm mũi dị ứng do phấn hoa','Allergic rhinitis due to pollen','ACTIVE'),
('J30.4','Viêm mũi dị ứng, không xác định','Allergic rhinitis, unspecified','ACTIVE'),
('J31.0','Viêm mũi mạn tính','Chronic rhinitis','ACTIVE'),
('J35.0','Viêm amydan mạn tính','Chronic tonsillitis','ACTIVE'),
('J40','Viêm phế quản, không xác định được là cấp tính hoặc mạn tính','Bronchitis, not specified as acute or chronic','ACTIVE'),
('J44.9','Bệnh phổi tắc nghẽn mạn tính, không xác định','Chronic obstructive pulmonary disease, unspecified','ACTIVE'),
('K04.0','Viêm tủy răng','Pulpitis','ACTIVE'),
('K05.1','Viêm lợi [nướu] mạn tính','Chronic gingivitis','ACTIVE'),
('K12.0','Loét miệng tái phát','Recurrent oral aphthae','ACTIVE'),
('K25.9','Loét dạ dày, không xác định mạn tính hoặc cấp tính, không xuất huyết hoặc thủng','Gastric ulcer, unspecified as acute or chronic, without haemorrhage or perforation','ACTIVE'),
('K26.9','Loét tá tràng, không xác định mạn tính hoặc cấp tính, không xuất huyết hoặc thủng','Duodenal ulcer, unspecified as acute or chronic, without haemorrhage or perforation','ACTIVE'),
('K29.7','Viêm dạ dày, không xác định','Gastritis, unspecified','ACTIVE'),
('K52.9','Viêm dạ dày - ruột và/hoặc viêm đại tràng không do nhiễm trùng, không xác định','Noninfective gastroenteritis and colitis, unspecified','ACTIVE'),
('K59.0','Táo bón','Constipation','ACTIVE'),
('K60.0','Nứt kẽ hậu môn cấp tính','Acute anal fissure','ACTIVE'),
('K76.0','Gan (biến đổi của gan) nhiễm mỡ, không phân loại mục khác','Fatty (change of) liver, not elsewhere classified','ACTIVE'),
('K80.2','Sỏi túi mật không kèm viêm túi mật','Calculus of gallbladder without cholecystitis','ACTIVE'),
('K81.9','Viêm túi mật, không xác định','Cholecystitis, unspecified','ACTIVE'),
('L03.9','Viêm mô bào, không xác định','Cellulitis, unspecified','ACTIVE'),
('L20.9','Viêm da cơ địa, không xác định','Atopic dermatitis, unspecified','ACTIVE'),
('L21.9','Viêm da dầu, không xác định','Seborrhoeic dermatitis, unspecified','ACTIVE'),
('L24.9','Viêm da tiếp xúc kích ứng, nguyên nhân không xác định','Irritant contact dermatitis, unspecified cause','ACTIVE'),
('L30.9','Viêm da, không xác định','Dermatitis, unspecified','ACTIVE'),
('L50.9','Bệnh mày đay, không xác định','Urticaria, unspecified','ACTIVE'),
('L70.0','Trứng cá thể thông thường','Acne vulgaris','ACTIVE'),
('M10.9','Bệnh gút, không xác định','Gout, unspecified','ACTIVE'),
('M15.9','Thoái hóa đa khớp, không xác định','Polyarthrosis, unspecified','ACTIVE'),
('M25.5','Đau khớp','Pain in joint','ACTIVE'),
('M54.2','Đau vai gáy','Cervicalgia','ACTIVE'),
('M54.4','Đau thắt lưng cấp tính kèm đau dây thần kinh hông to [dây thần kinh tọa]','Lumbago with sciatica','ACTIVE'),
('M62.8','Rối loạn xác định khác của cơ','Other specified disorders of muscle','ACTIVE'),
('M65.9','Viêm màng hoạt dịch và/hoặc viêm bao gân, không xác định','Synovitis and tenosynovitis, unspecified','ACTIVE'),
('M75.1','Hội chứng chóp xoay','Rotator cuff syndrome','ACTIVE'),
('M79.1','Đau cơ','Myalgia','ACTIVE'),
('M81.9','Loãng xương, không xác định','Osteoporosis, unspecified','ACTIVE'),
('N10','Viêm ống thận mô kẽ cấp tính','Acute tubulo-interstitial nephritis','ACTIVE'),
('N23','Cơn đau quặn thận không xác định','Unspecified renal colic','ACTIVE'),
('N30.0','Viêm bàng quang cấp tính','Acute cystitis','ACTIVE'),
('N30.9','Viêm bàng quang, không xác định','Cystitis, unspecified','ACTIVE'),
('N40','Phì đại [tăng sản] tuyến tiền liệt','Hyperplasia of prostate','ACTIVE'),
('N64.4','Đau vú','Mastodynia','ACTIVE'),
('N76.0','Viêm âm đạo cấp tính','Acute vaginitis','ACTIVE'),
('N94.6','Đau bụng kinh, không xác định','Dysmenorrhoea, unspecified','ACTIVE'),
('Z00.0','Khám sức khỏe tổng quát','General medical examination','ACTIVE')
ON DUPLICATE KEY UPDATE icd_code = diagnoses.icd_code;
COMMIT;
