-- 100 mục thuốc generic: hoạt chất, hàm lượng, dạng dùng.
-- Đối chiếu WHO EML 24 (2025): https://www.who.int/publications/i/item/B09474
-- Giá 0 là chưa cấu hình; không tạo tồn kho, số đăng ký hoặc nhà sản xuất.
-- Chạy lại giữ nguyên bản ghi đã có.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO medicines (code,name,active_ingredient,strength,dosage_form,unit,price,min_stock,status,created_at) VALUES
('TD001','Paracetamol 500 mg','Paracetamol','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD002','Paracetamol 250 mg','Paracetamol','250 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD003','Paracetamol 120 mg/5 mL','Paracetamol','120 mg/5 mL','Dung dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD004','Ibuprofen 200 mg','Ibuprofen','200 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD005','Ibuprofen 400 mg','Ibuprofen','400 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD006','Ibuprofen 100 mg/5 mL','Ibuprofen','100 mg/5 mL','Hỗn dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD007','Acid acetylsalicylic 100 mg','Acid acetylsalicylic','100 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD008','Acid acetylsalicylic 500 mg','Acid acetylsalicylic','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD009','Loratadine 10 mg','Loratadine','10 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD010','Loratadine 1 mg/mL','Loratadine','1 mg/mL','Dung dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD011','Prednisolone 5 mg','Prednisolone','5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD012','Prednisolone 25 mg','Prednisolone','25 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD013','Dexamethasone 0.5 mg','Dexamethasone','0.5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD014','Dexamethasone 4 mg','Dexamethasone','4 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD015','Hydrocortisone 100 mg','Hydrocortisone','100 mg','Bột pha tiêm','Lọ',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD016','Amoxicillin 250 mg','Amoxicillin','250 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD017','Amoxicillin 500 mg','Amoxicillin','500 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD018','Amoxicillin 1 g','Amoxicillin','1 g','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD019','Amoxicillin + acid clavulanic 500 mg + 125 mg','Amoxicillin + acid clavulanic','500 mg + 125 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD020','Amoxicillin + acid clavulanic 875 mg + 125 mg','Amoxicillin + acid clavulanic','875 mg + 125 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD021','Ampicillin 1 g','Ampicillin','1 g','Bột pha tiêm','Lọ',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD022','Cefalexin 250 mg','Cefalexin','250 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD023','Cefalexin 500 mg','Cefalexin','500 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD024','Cefazolin 1 g','Cefazolin','1 g','Bột pha tiêm','Lọ',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD025','Ceftriaxone 1 g','Ceftriaxone','1 g','Bột pha tiêm','Lọ',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD026','Cefotaxime 1 g','Cefotaxime','1 g','Bột pha tiêm','Lọ',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD027','Doxycycline 100 mg','Doxycycline','100 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD028','Azithromycin 250 mg','Azithromycin','250 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD029','Azithromycin 500 mg','Azithromycin','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD030','Clarithromycin 250 mg','Clarithromycin','250 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD031','Clarithromycin 500 mg','Clarithromycin','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD032','Ciprofloxacin 250 mg','Ciprofloxacin','250 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD033','Ciprofloxacin 500 mg','Ciprofloxacin','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD034','Metronidazole 200 mg','Metronidazole','200 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD035','Metronidazole 400 mg','Metronidazole','400 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD036','Metronidazole 500 mg','Metronidazole','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD037','Nitrofurantoin 100 mg','Nitrofurantoin','100 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD038','Sulfamethoxazole + trimethoprim 400 mg + 80 mg','Sulfamethoxazole + trimethoprim','400 mg + 80 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD039','Sulfamethoxazole + trimethoprim 800 mg + 160 mg','Sulfamethoxazole + trimethoprim','800 mg + 160 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD040','Sulfamethoxazole + trimethoprim 200 mg + 40 mg/5 mL','Sulfamethoxazole + trimethoprim','200 mg + 40 mg/5 mL','Hỗn dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD041','Cloxacillin 500 mg','Cloxacillin','500 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD042','Clindamycin 150 mg','Clindamycin','150 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD043','Allopurinol 100 mg','Allopurinol','100 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD044','Fluconazole 50 mg','Fluconazole','50 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD045','Itraconazole 100 mg','Itraconazole','100 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD046','Griseofulvin 250 mg','Griseofulvin','250 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD047','Miconazole 2%','Miconazole','2%','Kem bôi da','Tuýp',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD048','Nystatin 100000 IU/mL','Nystatin','100000 IU/mL','Hỗn dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD049','Aciclovir 200 mg','Aciclovir','200 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD050','Aciclovir 200 mg/5 mL','Aciclovir','200 mg/5 mL','Dung dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD051','Albendazole 400 mg','Albendazole','400 mg','Viên nhai','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD052','Mebendazole 100 mg','Mebendazole','100 mg','Viên nhai','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD053','Mebendazole 500 mg','Mebendazole','500 mg','Viên nhai','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD054','Ivermectin 3 mg','Ivermectin','3 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD055','Praziquantel 600 mg','Praziquantel','600 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD056','Amlodipine 5 mg','Amlodipine','5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD057','Verapamil 40 mg','Verapamil','40 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD058','Losartan 25 mg','Losartan','25 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD059','Losartan 50 mg','Losartan','50 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD060','Losartan 100 mg','Losartan','100 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD061','Enalapril 2.5 mg','Enalapril','2.5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD062','Enalapril 5 mg','Enalapril','5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD063','Enalapril 10 mg','Enalapril','10 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD064','Verapamil 80 mg','Verapamil','80 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD065','Hydrochlorothiazide 12.5 mg','Hydrochlorothiazide','12.5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD066','Hydrochlorothiazide 25 mg','Hydrochlorothiazide','25 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD067','Furosemide 20 mg','Furosemide','20 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD068','Furosemide 40 mg','Furosemide','40 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD069','Spironolactone 25 mg','Spironolactone','25 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD070','Bisoprolol 1.25 mg','Bisoprolol','1.25 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD071','Bisoprolol 5 mg','Bisoprolol','5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD072','Loperamide 2 mg','Loperamide','2 mg','Viên nang','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD073','Calcium nguyên tố 500 mg','Calcium nguyên tố','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD074','Simvastatin 10 mg','Simvastatin','10 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD075','Simvastatin 20 mg','Simvastatin','20 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD076','Simvastatin 40 mg','Simvastatin','40 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD077','Clopidogrel 75 mg','Clopidogrel','75 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD078','Isosorbide dinitrate 5 mg','Isosorbide dinitrate','5 mg','Viên ngậm dưới lưỡi','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD079','Digoxin 250 microgam','Digoxin','250 microgam','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD080','Metformin 500 mg','Metformin','500 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD081','Gliclazide 30 mg','Gliclazide','30 mg','Viên giải phóng có kiểm soát','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD082','Gliclazide 60 mg','Gliclazide','60 mg','Viên giải phóng có kiểm soát','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD083','Gliclazide 80 mg','Gliclazide','80 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD084','Omeprazole 10 mg','Omeprazole','10 mg','Viên nang bao tan trong ruột','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD085','Omeprazole 20 mg','Omeprazole','20 mg','Viên nang bao tan trong ruột','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD086','Omeprazole 40 mg','Omeprazole','40 mg','Viên nang bao tan trong ruột','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD087','Metoclopramide 10 mg','Metoclopramide','10 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD088','Ondansetron 4 mg','Ondansetron','4 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD089','Ondansetron 8 mg','Ondansetron','8 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD090','Lactulose 3.35 g/5 mL','Lactulose','3.35 g/5 mL','Dung dịch uống','Chai',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD091','Senna (sennosides) 7.5 mg','Senna (sennosides)','7.5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD092','Salbutamol 100 microgam/liều','Salbutamol','100 microgam/liều','Bình xịt định liều','Bình',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD093','Budesonide 200 microgam/liều','Budesonide','200 microgam/liều','Bình xịt định liều','Bình',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD094','Budesonide 100 microgam/liều','Budesonide','100 microgam/liều','Bình xịt định liều','Bình',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD095','Levothyroxine 50 microgam','Levothyroxine','50 microgam','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD096','Levothyroxine 100 microgam','Levothyroxine','100 microgam','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD097','Acid folic 5 mg','Acid folic','5 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD098','Acid ascorbic 50 mg','Acid ascorbic','50 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD099','Pyridoxine 25 mg','Pyridoxine','25 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP),
('TD100','Thiamine 50 mg','Thiamine','50 mg','Viên nén','Viên',0,0,'ACTIVE',CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE code = medicines.code;
COMMIT;
